### ISSUE TITLE
Doesn't it has any method to fix the width?

### ISSUE THREAD

**Issue by praveenkumar56060** [ermalkaleci/CarbonKit#103]
Can we have a method to assign the fixed the width for `CarbonTabSwipeNavigation`

**Comment by ermalkaleci** [comment]
There is a method for fixed width. Checkout the example project

**Comment by praveenkumar56060** [comment]
[carbonTabSwipeNavigation.carbonSegmentedControl setWidth:113.0 forSegmentAtIndex:i];

Right?
