### ISSUE TITLE
Viewcontrollers not aligning correctly after swiping

### ISSUE THREAD

**Issue by stevenbr91** [ermalkaleci/CarbonKit#106]
Detailed description : http://stackoverflow.com/questions/37391611/carbonkit-carbontabswipenavigation-viewcontrollers-not-aligning-correctly

![image](https://cloud.githubusercontent.com/assets/3242635/15471544/c095d75a-20f6-11e6-990c-a6e8f20c9d30.jpeg)

seems to happen when using a toolbar and when inserting the view with "insertIntoRootViewController", the red line on the right is a part of the second viewcontroller.

**Comment by ermalkaleci** [comment]
Hey @stevenbr91 can you share more info?

**Comment by ermalkaleci** [comment]
can you record a video?

**Comment by stevenbr91** [comment]
Made a video, hope it helps you understand the problem:
https://youtu.be/FJMyb7EDrd4

**Comment by ermalkaleci** [comment]
@stevenbr91 you are misaligning.

**Comment by mobile-sonaris** [comment]
Hello, 
Sorry, I am here.
You can update me

**Comment by ermalkaleci** [comment]
are you using any fixed width?

**Comment by mobile-sonaris** [comment]
No, yet. Can you send me content to be my target again?

**Comment by ermalkaleci** [comment]
I am not sure what you mean?
I seems like there is a negative margin of the left and positive margin on the right. Even the indicator isn't position right

**Comment by mobile-sonaris** [comment]
I want to understand and update my current project using CarbonKit. 
So in order to understand it, I think I can support issue fixing. 
I mean what I can fix issues right now. 
Thanks

**Comment by ermalkaleci** [comment]
@mobile-sonaris are you @stevenbr91 ? 😄

**Comment by mobile-sonaris** [comment]
No, I am newbie in here. 
I want awesome developer history in git community and so I choose your organization as contributer. So you can give me job for CarbonKit issues and ..... 
How about you think?

**Comment by ermalkaleci** [comment]
😃 Great! You're welcome!
I am a little busy right know, but you can take a look how the lib is build and we can discuss latter for some small issues that happen on same special cases. Thank you 👍

**Comment by mobile-sonaris** [comment]
Okay, thanks , but you don't need to worry about my skills, I already used CarbonKit a lot of time
So I had got a clear picture of it 
If you are available, please message me. I will accept your all request
Thanks again.

**Comment by mobile-sonaris** [comment]
PS: l love to use CarbonKit

**Comment by stevenbr91** [comment]
hmm, I found the problem. For some reason the "clip subviews" was disabled on the viewcontrollers that were displayed in the tabs. checking the checkbox in the storyboard did fix the problem. Sorry and Thanks for the help 👍 

btw, i dont know mobile-sonaris lol

**Comment by ermalkaleci** [comment]
@stevenbr91 hi wrote after you and I thought was you 😅

**Comment by mobile-sonaris** [comment]
Hi
