### ISSUE TITLE
Infinite Tab Scrolling

### ISSUE THREAD

**Issue by hashemp206** [ermalkaleci/CarbonKit#108]
I'm looking for a way to implement infinite tab scroller like the image below:
<img width="123" alt="screen shot 2016-06-02 at 7 09 48 pm" src="https://cloud.githubusercontent.com/assets/3206748/15754686/a7a742fe-290e-11e6-8e1b-0fd887431b27.png">

courtesy of an app named [DownTown](https://itunes.apple.com/us/app/id908014422)

so is there any way to add a feature to this component to handle infinite tab scrolling?

I have developed a component named: [InfinitePageController ](https://github.com/hashemp206/HAInfinitePageController) but it has some glitches

**Comment by ermalkaleci** [comment]
This is hard and not really useful. My opinion :)

**Comment by hashemp206** [comment]
the component idea was great for me, it is some how fancy for me. but I tried to challenge my knowledge, but I came a cross a barrier which I couldn't solve alone! I need someone help. thanks
