### ISSUE TITLE
center tab items

### ISSUE THREAD

**Issue by mrbayri** [ermalkaleci/CarbonKit#119]
i solve with this code

`CGFloat selfWidth = CGRectGetWidth(self.bounds);
        if ( [_carbonSegmentedControl getWidth]<CGRectGetWidth(self.bounds))
        {
            CGFloat difference = selfWidth -  [_carbonSegmentedControl getWidth];
            self.frame = CGRectMake(difference/2.0f, 0, selfWidth, CGRectGetHeight(self.bounds));
            
        }
        else
        {
            CGRect frame = self.frame;
            if (!CGRectEqualToRect(frame, CGRectMake(0, 0, selfWidth, CGRectGetHeight(self.bounds))))
            {
                self.frame = CGRectMake(0, 0, selfWidth, CGRectGetHeight(self.bounds));
            }
        }`

but when i click table view item and turn back again tab items float left

**Comment by MobileMon** [comment]
How to fix the items floating back left? I have the same issue

**Comment by mrbayri** [comment]
you need to use one view for carbonKit and connect other views, however navigation controller need to be connected view which is carbonKit.

**Comment by MobileMon** [comment]
@mrbayri I don't understand what you mean

**Comment by mrbayri** [comment]
u only need to add navigation controller to carbonKit View

**Comment by MobileMon** [comment]
Still don't understand...
