### ISSUE TITLE
Programmatically change to a tab View (Index) at button click of ViewController which belongs to tab index 0  ?

### ISSUE THREAD

**Issue by xplorerakesh** [ermalkaleci/CarbonKit#123]
![simulator screen shot 13-sep-2016 11 28 53 am 1](https://cloud.githubusercontent.com/assets/2862131/18583434/2d073ad2-7c28-11e6-919a-580466cb6c0e.png)

hello can i call Move to carbonTabSwipeNavigation from Index : 0 to Index:1.. 

**according to above Image at next button click i want to go Commodity Details Tab**

Example : Using Carbon kit with 3 UIviewcontroller . when user click UIbutton at ViewController One so i want my carbonTabSwipeNavigation move to Index :1 and uiViewController Two Will Appear on the screen .. If its possible , so share code with me ..Thanks :)

**Comment by GaneshKumarSelvam** [comment]
Got any Solution for this?
