### ISSUE TITLE
How to hide bottom line of tool bar?

### ISSUE THREAD

**Issue by O-mkar** [ermalkaleci/CarbonKit#124]
How do i hide bottom line on the tool bar any idea?

**Comment by sullivanv** [comment]
(in swift) carbonTabSwipeNavigation.setIndicatorHeight(0)

**Comment by trangnttVentuso** [comment]
Hi ,
I wanna hide bottom line 
please see screenshot in red rectangle.
https://cloud.githubusercontent.com/assets/27410015/24996446/17fb3920-205d-11e7-8861-e056eebd8f1a.png
Thank so much.

**Comment by O-mkar** [comment]
@trangnttVentuso carbonTabSwipeNavigation.setIndicatorHeight(0)

**Comment by sixtysticks** [comment]
@trangnttVentuso I know it's a bit late (and issue's been closed) but I came across this issue and fixed it with the following:

```
// Objective-C
[carbonTabSwipeNavigation.toolbar setClipsToBounds:YES];

// Swift
carbonTabSwipeNavigation.toolbar.clipsToBounds = YES
```

Hope that helps anyone else :)
