### ISSUE TITLE
Swift 3.0 problem

### ISSUE THREAD

**Issue by mrbayri** [ermalkaleci/CarbonKit#128]
I have lots of errors and warnings how to convert swift 3.0 ?

**Comment by narasimhanallamsetty** [comment]
I have integrated code with swift 3. Please check below code.


First drag and drop carbon kit library files into your app. Then
Declare an array like this var detailsArray = NSArray()

Initialise same array like this detailsArray =   ["one","two","three","four","five","six",UIImage(named: "profile")!]  // I have added image also as part of menu items

in the viewDidLoad
{
carbonTabSwipeNavigation = CarbonTabSwipeNavigation(items: detailsArray as [AnyObject], delegate: self)

carbonTabSwipeNavigation.insert(intoRootViewController: self)

carbonTabSwipeNavigation.toolbar.isTranslucent = false
        //carbonTabSwipeNavigation.setIndicatorColor(color)
        carbonTabSwipeNavigation.setTabExtraWidth(30)
                
        carbonTabSwipeNavigation.carbonSegmentedControl?.setWidth(80, forSegmentAt: 0)
        carbonTabSwipeNavigation.carbonSegmentedControl?.setWidth(120, forSegmentAt: 1)
        carbonTabSwipeNavigation.carbonSegmentedControl?.setWidth(80, forSegmentAt: 2)
        carbonTabSwipeNavigation.carbonSegmentedControl?.indicatorPosition = .top
        carbonTabSwipeNavigation .setTabBarHeight(50)//tab bar height
        
        
        carbonTabSwipeNavigation.setNormalColor(UIColor.black, font: someFont)
        carbonTabSwipeNavigation.setSelectedColor(UIColor.black, font: someFont)
        carbonTabSwipeNavigation.setIndicatorColor(UIColor.black)
        

}

//carbon kit methods
 func barPosition(for carbonTabSwipeNavigation: CarbonTabSwipeNavigation) -> UIBarPosition {
        
        return UIBarPosition.bottom
    }
    
    func carbonTabSwipeNavigation(_ carbonTabSwipeNavigation: CarbonTabSwipeNavigation, viewControllerAt index: UInt) -> UIViewController
    {
        
        switch index
        {
        case 0:
            return self.storyboard!.instantiateViewController(withIdentifier: "vitalsView") as! VitalsViewController
           
        case 1:
            return self.storyboard!.instantiateViewController(withIdentifier: "medicationsView") as! MedicationsViewController
        
default:
            
            return self.storyboard!.instantiateViewController(withIdentifier: "surgeriesView") as! SurgeriesViewController
            
        }
       
    }

func carbonTabSwipeNavigation(_ carbonTabSwipeNavigation: CarbonTabSwipeNavigation, didMoveAt index: UInt) {
        NSLog("Did move at index: %ld", index)
        
}

**Comment by mrbayri** [comment]
thanks

**Comment by StevenArmandLee** [comment]
it does not work on me when i added picture it will crash

"Thread 1: signal SIGABRT"

here is my code

```
let items: NSArray = [UIImage(named: "back"), "b"]
        let carbonTabSwipeNavigation = CarbonTabSwipeNavigation(items: items as [AnyObject], delegate: self)
        carbonTabSwipeNavigation.toolbar.barTintColor = UIColor(red: 255/255.0, green: 82/255.0, blue: 82/255.0, alpha: 1)
        carbonTabSwipeNavigation.toolbar.isTranslucent = false
        carbonTabSwipeNavigation.setIndicatorColor(UIColor(red: 255/255.0, green: 255/255.0, blue: 255/255.0, alpha: 1))
        carbonTabSwipeNavigation.setNormalColor(UIColor(red: 255/255.0, green: 255/255.0, blue: 255/255.0, alpha: 0.5))
        carbonTabSwipeNavigation.setSelectedColor(UIColor(red: 255/255.0, green: 255/255.0, blue: 255/255.0, alpha: 1))
        carbonTabSwipeNavigation.insert(intoRootViewController: self)
```

**Comment by narasimhanallamsetty** [comment]
It's working for us. Please check with example app from carbon kit.

**Comment by StevenArmandLee** [comment]
@narasimhanallamsetty  hi it's working fine now, i forgot to unwrap the image.

thanks.

btw do you know how to set the size of the image? because for mine it automatically becomes bigger to fit the size of the bar
