### ISSUE TITLE
How to set the size of the tab image`

### ISSUE THREAD

**Issue by StevenArmandLee** [ermalkaleci/CarbonKit#133]
Hi, I'm having a problem where my items the image looks too big in my project.

it seems that the image is resized to fit the frame, I would like it to be the size of the assets so it is not being zoomed and looks pixelated.

**Comment by ermalkaleci** [comment]
@StevenArmandLee It's a UISegmentedControl so make sure you're using your assets correctly.
![simulator screen shot 13 oct 2016 21 54 30](https://cloud.githubusercontent.com/assets/3055344/19364749/b5338a10-918f-11e6-8cb5-d8eb0d503d00.png)

**Comment by StevenArmandLee** [comment]
@ermalkaleci Hi, I'm wondering if you could give me the code that you use to do that? I've been searching to do that however I failed to achieve the result that you did.


thanks.

**Comment by StevenArmandLee** [comment]
this is two different thing that I tried and not working

`let items:NSArray = [UIImage(named: "contactlist")!.resizableImage(withCapInsets: UIEdgeInsets(top: 10, left: 10, bottom: 10, right: 10)), UIImage(named: "chatlist")!.stretchableImage(withLeftCapWidth: 20, topCapHeight: 20)]`

I even tried to ask my designer to make the canvas of the image bigger and I does not work also.

thanks.

**Comment by ermalkaleci** [comment]
There is no code

**Comment by StevenArmandLee** [comment]
@ermalkaleci I wonder if you can explain it to me in more detail how you achieve this?
I have my image small and it is being stretched.

I'm so sorry that I have a slow understanding.

thanks.

**Comment by StevenArmandLee** [comment]
Hi, I've finally found what you meant, thank you so much for the help

in case anybody is having the same problem, here is the solution.

> I moved my x1 image to x2 image, so it will not stretch.
