### ISSUE TITLE
Adding view controller to Carbon kit initially shows black space above view. Any Solution?

### ISSUE THREAD

**Issue by bhallamohit** [ermalkaleci/CarbonKit#137]
![thumb_screen shot 2016-11-03 at 3 05 50 pm_1024](https://cloud.githubusercontent.com/assets/18654188/19961365/4a4fa87e-a1d8-11e6-944b-daeaac414419.jpg)

black space disappears after scrolling up.

![thumb_screen shot 2016-11-03 at 3 06 07 pm_1024](https://cloud.githubusercontent.com/assets/18654188/19961439/a836e7a4-a1d8-11e6-9fcb-dffd99152428.jpg)

**Comment by bhallamohit** [comment]
yes i solved it. Actually that was third party library issue.

**Comment by IOSDeveloperProgrammer** [comment]
@bhallamohit  how did you resolved issue ?  I'm getting same issue , getting when will move main to another VC,  and getting back to main VC showing white space . i'm stuck .

**Comment by sunitadoubleeye** [comment]
@IOSDeveloperProgrammer What other libraries you are using in addition this one?
