### ISSUE TITLE
Change label on one segment dynamically

### ISSUE THREAD

**Issue by CedricVanAsch** [ermalkaleci/CarbonKit#138]
Hi,

Is there any way to change the text in the label for one segment dynamically? I start with my items in the ViewDidLoad, but when a user pressed a certain category, I want the label on that tab (segment) to change into the selected category.

I found how to change the background color for a certain segment, but not how to modify the text.  
`carbonTabSwipeNavigation.carbonSegmentedControl?.segments![2].backgroundColor = UIColor.blueColor()`

**Comment by ankitjaiswal1994** [comment]
@CedricVanAsch Any solution ?
