### ISSUE TITLE
how to divide bar item of CarbonTabSwipeNavigation equal width?

### ISSUE THREAD

**Issue by subhash08** [ermalkaleci/CarbonKit#140]
Only two item , available width will divide equal to both items like in image, how to achieve this
 

![untitled](https://cloud.githubusercontent.com/assets/11552671/20832010/d26f2d60-b8ad-11e6-88ab-3a147c047c51.png)

**Comment by mr746866** [comment]
I have the same problem.

**Comment by shejis** [comment]
You can achieve  like this 

let widthOfTabIcons = phonescreenWidth/2
    carbonTabSwipeNavigation.carbonSegmentedControl!.setWidth(widthOfTabIcons, forSegmentAt: 0)
    carbonTabSwipeNavigation.carbonSegmentedControl!.setWidth(widthOfTabIcons, forSegmentAt: 1)

**Comment by jonysingla** [comment]
Only three item , available width will divide equal to both items like in image, how to achieve this.

![screen shot 2017-10-28 at 11 20 20 am](https://user-images.githubusercontent.com/7313159/32131752-9ddba93c-bbd3-11e7-87b3-5a0d8b927c3f.png)

**Comment by jonysingla** [comment]
I am trying this but not resolve my problem:           
        let screenSize: CGRect = UIScreen.main.bounds
        let screenWidth = screenSize.width/3
        print(screenWidth). // Print 125
        carbonTabSwipeNavigation.carbonSegmentedControl!.setWidth(screenWidth, forSegmentAt: 0)
        carbonTabSwipeNavigation.carbonSegmentedControl!.setWidth(screenWidth, forSegmentAt: 1)
        carbonTabSwipeNavigation.carbonSegmentedControl!.setWidth(screenWidth, forSegmentAt: 2)

**Comment by dhiraj-quantumsoftech** [comment]
Not working above solution
