### ISSUE TITLE
how to show Indicator on top of Bar?

### ISSUE THREAD

**Issue by O16MuhammadAhmedBaig** [ermalkaleci/CarbonKit#159]
is there any option to show Indicator on top of bar? not on bottom?

**Comment by MuhammadMurtazaMemon** [comment]
Hey you have to just do `
        tabNavigation = CarbonTabSwipeNavigation(items: tabtitles, delegate: self)
        tabNavigation.insert(intoRootViewController: self)
        tabNavigation.carbonSegmentedControl?.indicatorPosition = .top`
