### ISSUE TITLE
Sometimes don't show

### ISSUE THREAD

**Issue by NorbertSzydlowski** [ermalkaleci/CarbonKit#16]

**Comment by ermalkaleci** [comment]
You mean SwipeRefresh don't show when you pull down the tableview?

**Comment by NorbertSzydlowski** [comment]
Yes. With uicollectionview 
29 kwi 2015 18:43 Ermal Kaleci <notifications@github.com> napisał(a):You mean SwipeRefresh don't show when you pull down the tableview?

**Comment by ermalkaleci** [comment]
Have you enabled "Bounce Vertically"?

**Comment by ermalkaleci** [comment]
Hi @NorbertSzydlowski 
Please, check the latest commit. I think I found and fixed it.
