### ISSUE TITLE
UIControlEventValueChanged is not fired on iOS11 beta2

### ISSUE THREAD

**Issue by htteng1976** [ermalkaleci/CarbonKit#167]
Hi CarbonKit team,

Today we just found a issue about menu tapping on iOS11 beta 2.
When we tap the menu item, [CarbonTabSwipeNavigation segmentedTapped:] is not called.
It means the UIControlEventValueChanged event is not notified by iOS.
We download the sample project and found this issue could be reproduced as well. (Tap the menu item and nothing happen)

Since iOS11 is still in beta version, we cannot make sure Apple will fix it before final release.
Just share you the bad news we found and keep observing the behavior on next beta version.

Best regards,
Brandon

**Comment by ulidev** [comment]
Yep, I found too. I'm trying to find a reason and fix it.
Tell me if you find a solution, I will tell you too.

Thanks.

**Comment by ulidev** [comment]
I filed a radar: ://32968802

**Comment by ulidev** [comment]
I did a workarround, when Apple fix this bug, use the main repo --> https://github.com/ulidev/CarbonKit

**Comment by htteng1976** [comment]
Dear ulidev,

Thanks for your response and quick workaround :)
We tried your workaround but found another side effect.
The focus is always moving left and out of the window as long as adding more menu items.
Just feedback the test result.

<img width="312" alt="2017-06-26 10 45 16" src="https://user-images.githubusercontent.com/813471/27522987-a2bedc36-5a5c-11e7-8f81-c4c4c5ca333f.png">

**Comment by imunique-ZJ** [comment]
I think I found another workaround.
- Modify the constraints of the toolbar in the `- (void)addToolbarIntoSuperview` method to adjust the paddings of the toolbar.
- In the `- (void)createTabSwipeScrollViewWithItems:(NSArray *)items` method, create a `UIBarButtonItem` and add the `CarbonTabSwipeScrollView` as child view.
- Add the `UIBarButtonItem` to the toolbar.
- Remove the constraints of the `CarbonTabSwipeScrollView`.

The result will look like this.
![screenshot](https://user-images.githubusercontent.com/4104660/27615566-a7fce23a-5bdb-11e7-9d2e-35fb76a1130f.png)

I create a gist [here](https://gist.github.com/imunique-ZJ/81fbac17ac6d58a8669f039fba51865f).
Hope this could help you.

**Comment by htteng1976** [comment]
Hi ZJ, 

I tried your patch and it works pretty well.
Thank you very much :)

**Comment by ermalkaleci** [comment]
fixed

**Comment by masoningram1369** [comment]
CarbonKit is not working  when user change  rotation portrait to landscape. segmentcontol bar is not adjust with landscape mode. we have not used in fixed width for segment bar.
would you please take a look on this issue?
