### ISSUE TITLE
tab navigation does not work on ios 11.

### ISSUE THREAD

**Issue by zeeshansuleman** [ermalkaleci/CarbonKit#175]

**Comment by Pratik948** [comment]
I'm also facing the same issue, tapping on tab item doesn't scroll to the viewcontroller, in fact swiping viewcontroller manually does navigate to that view controller. I think something is messed up in `CarbonTabSwipeSegmentedControl`.

**Comment by Pratik948** [comment]
I think this issue was solved in a [commit](https://github.com/ermalkaleci/CarbonKit/commit/759bdf671bfdad0f10c5d33667f6411ecacbf72d). I think there are some changes with bars in iOS 11 including `UINavigationBar`, `UIToolbar` and i didn't dig enough in `UITabBar`.

**Comment by mberndt92** [comment]
@ermalkaleci : I agree with @Pratik948 , this is not an issue in current library version. You should close the issue.

**Comment by vinayakpal** [comment]
im also facing the same problem so how can i solve this problem in ios 11
