### ISSUE TITLE
Change Tab Indicator

### ISSUE THREAD

**Issue by marcoslacerda** [ermalkaleci/CarbonKit#178]
Hello,

First of all I would like to congratulate you for the excellent work!
CarbonKit saved me!

I wanted to know if there is a way to change the width of the bookmark, just as I can change the height using the `setIndicatorHeight` method.

Similar this:

<img width="374" alt="screen shot 2017-09-14 at 10 51 22" src="https://user-images.githubusercontent.com/4759987/30433367-acfba8ec-993a-11e7-94b2-53ac5ae699b8.png">

Thanks

**Comment by ermalkaleci** [comment]
@marcoslacerda There's no such method but you can do it just by adding a custom view into indicator (UIImageView)
Here's obj-c example:

`[carbonTabSwipeNavigation setIndicatorColor:nil];
UIImageView *indicator = carbonTabSwipeNavigation.carbonSegmentedControl.indicator;

UIView *subview = [[UIView alloc] init];
subview.backgroundColor = [UIColor redColor];
[indicator addSubview:subview];

subview.translatesAutoresizingMaskIntoConstraints = false;
[[subview.widthAnchor constraintEqualToConstant:20] setActive:true];
[[subview.centerXAnchor constraintEqualToAnchor:indicator.centerXAnchor constant:0] setActive:true];
[[subview.topAnchor constraintEqualToAnchor:indicator.topAnchor constant:0] setActive:true];
[[subview.bottomAnchor constraintEqualToAnchor:indicator.bottomAnchor constant:0] setActive:true];`

![simulator screen shot - iphone 7 plus - 2017-09-15 at 13 53 46](https://user-images.githubusercontent.com/3055344/30481129-511efe78-9a1d-11e7-8e56-b0b049721f28.png)

**Comment by marcoslacerda** [comment]
@ermalkaleci Thank you for your help!

You save my Life ! 

=D
