### ISSUE TITLE
Clicking on tab does not scroll and change the index . (IOS 11)

### ISSUE THREAD

**Issue by zeeshansuleman** [ermalkaleci/CarbonKit#180]

**Comment by ermalkaleci** [comment]
Make sure you are using latest version.

**Comment by zeeshansuleman** [comment]
@ermalkaleci why did you close this issue , i am using latest version of library still it does not work on ios 11.

**Comment by zeeshansuleman** [comment]
did not fixed in latest version as well.

**Comment by mucoolcp** [comment]
With me too. It's not fixed... :(
