### ISSUE TITLE
My app suddenly crashed after I migration from swift 3 to swift 4 in Xcode 9 

### ISSUE THREAD

**Issue by Darapo** [ermalkaleci/CarbonKit#184]
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: carbonTabSwipeNavigation:viewControllerAtIndex: unrecognized selector sent to instance
How should I fix this problem? Please help

**Comment by kristiyandobrev** [comment]
Did you managed to solve that ?

**Comment by Darapo** [comment]
When I migrate from swift 3 to swift 4 Xcode recommend to change Swift 3
@objc inference in build setting from ON to default. That when I got crush
If I'm still set swift 3 @objc inference ON it no error or crush.

**Comment by ermalkaleci** [comment]
@Darapo error is clear. method `carbonTabSwipeNavigation:viewControllerAtIndex` isn;t defined on delegated object
