### ISSUE TITLE
Prevent CarbonTabSwipeNavigation from bouncing

### ISSUE THREAD

**Issue by kristiyandobrev** [ermalkaleci/CarbonKit#187]
Is it possible to prevent `CarbonTabSwipeNavigation` from bouncing (left and right) ?

**Comment by ermalkaleci** [comment]
@kristiyandobrev YES
`@property(weak, nonatomic) UIScrollView *pagesScrollView;`
disable bouncing

**Comment by kristiyandobrev** [comment]
@ermalkaleci 

That disables the swiping between pages not the bouncing of the `CarbonTabSwipeNavigation`

**Comment by ermalkaleci** [comment]
@kristiyandobrev 
check properties here
https://github.com/ermalkaleci/CarbonKit/blob/master/CarbonKit/CarbonTabSwipeNavigation.h
