### ISSUE TITLE
Prevent navigation items from bouncing left and right

### ISSUE THREAD

**Issue by kristiyandobrev** [ermalkaleci/CarbonKit#188]
I have my `CarbonTabSwipeNavigation` like: 

```
private(set) lazy var tabSwipeNavigation: CarbonTabSwipeNavigation = {
        let segmentControlWidth = UIScreen.main.bounds.size.width / CGFloat(self.tabPagerNavigationItems.count)
        let carbonTabSwipeNavigation = CarbonTabSwipeNavigation(items: self.tabPagerNavigationItems, delegate: self)
        carbonTabSwipeNavigation.carbonSegmentedControl?.backgroundColor = .white
        for (index, element) in self.tabPagerNavigationItems.enumerated() {
            carbonTabSwipeNavigation.carbonSegmentedControl?.setWidth(segmentControlWidth, forSegmentAt: index)
        }
        carbonTabSwipeNavigation.setNormalColor(someColor)
        carbonTabSwipeNavigation.setSelectedColor(someColor2)
        carbonTabSwipeNavigation.setIndicatorColor(someColor3)
        carbonTabSwipeNavigation.setIndicatorHeight(2)
        return carbonTabSwipeNavigation
    }()
```

And it looks like:

<img width="377" alt="screen shot 2017-10-10 at 08 32 39" src="https://user-images.githubusercontent.com/8437817/31372519-62e85e1a-ad96-11e7-9290-6eb354bb10ff.png">

The problem is that the items with the icons are bouncing left or right whenever I try to scroll them, meaning that the items are going off the screen:

<img width="377" alt="test" src="https://user-images.githubusercontent.com/8437817/31372567-afbf4d8e-ad96-11e7-96c2-e854dd4dd44f.png">

I have tried to to add `carbonTabSwipeNavigation.pagesScrollView?.bounces = false` but that only prevents the swiping to to the next coontroller in the `carbonTabSwipeNavigation`. 

Any ideas if disabling the bouncing of the navigation items is possible ?

**Comment by ermalkaleci** [comment]
@kristiyandobrev It seems like a bug. Please can you share your project environment (iOS, xCode)?

**Comment by kristiyandobrev** [comment]
`iOS 11.*` and `XCode 9.*`

**Comment by ermalkaleci** [comment]
can't reproduce it. can you record your screen?

**Comment by kristiyandobrev** [comment]
Alright. I managed to solve it. I had to add `carbonTabSwipeScrollView.isScrollEnabled = false`. It is undoubtedly a really simple fix but unfortunately undocumented.
