### ISSUE TITLE
carbonSegmentedControl Not scrolled when calling setCurrentTabIndex

### ISSUE THREAD

**Issue by Pratik948** [ermalkaleci/CarbonKit#200]
I am using (2.2.2) version of `CarbonKit`, the issue is when i call `[_carbonTabSwipeNavigation setCurrentTabIndex:index withAnimation:YES];`, `carbonSegmentedControl` is not getting scrolled neither the indicator. This used to work perfect in previous version (2.1.10) of `CarbonKit`

**Comment by Shahbaz-Akram** [comment]
If you want to custom move then use it 
[carbonTabSwipeNavigation setCurrentTabIndex:1];

**Comment by Pratik948** [comment]
@Shahbaz-Akram That is not what i asked, i meant the tab strip does not scroll when called `[_carbonTabSwipeNavigation setCurrentTabIndex:index withAnimation:YES];`, view controller on the specific index scrolls fine but the tab on the top does not scroll like it used to work in previous version of this lib.

**Comment by Pratik948** [comment]
I don't know why it wasn't working in my current project, i can't reproduce the issue in example project or another demo i've created.
well, for my current project i've user a workaround like below code.

`- (void)carbonTabSwipeNavigation:(CarbonTabSwipeNavigation *)carbonTabSwipeNavigation didMoveAtIndex:(NSUInteger)index {
    UIView *view = [[self.carbonTabSwipeNavigation.carbonSegmentedControl segments] objectAtIndex:index];
    [self.carbonTabSwipeNavigation.carbonTabSwipeScrollView scrollRectToVisible:view.frame animated:YES];
    [self adjustTitleViewWithIndex:index animated:_isFirstTabDisplayed];
    _isFirstTabDisplayed=YES;
}
`
