### ISSUE TITLE
Touch on tab title header not working in xode 9 and ios 11

### ISSUE THREAD

**Issue by vinayakpal** [ermalkaleci/CarbonKit#201]
in xode 8 and ios 9 its working great but but when i updated to xcode 9 touches on header title to move to next tab is not working please help.

**Comment by Pratik948** [comment]
@vinayakpal are you using latest version of `CarbonKit`? This issue was solved in #175 
@ermalkaleci is this issue duplicate?

**Comment by vinayakpal** [comment]
@Pratik948 i install carbon kit when i was using xocde 8 through pod file. Should i update my pod file to upgrade to latest vesrion or is there any other method to get the latest code in package?

**Comment by Pratik948** [comment]
It seems you've older version of `CarbonKit`. Try `pod repo update` then `pod install` in your workspace directory.

**Comment by vinayakpal** [comment]
can i do it with manua process as well as i have manual file exist if i don't want to use pod

**Comment by Pratik948** [comment]
Remove `CarbonKit` from your project and download and re-add source to your project.

**Comment by vinayakpal** [comment]
i dod the same but now all the delegate method could not able to read the new carbon kit class.

**Comment by vinayakpal** [comment]
@Pratik948  thank you for your guidence. i able to resolve issues and now i have updated version and it working now.
