### ISSUE TITLE
Swift 1.2 problem with array

### ISSUE THREAD

**Issue by ijpe** [ermalkaleci/CarbonKit#22]
I have a problem in Swift, my problem is with necessary array, i receive this error....
 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: 0)'

My code is this
var names = ["About Redar", "Privacy Policy", "Terms of Use"]
        tabSwipe = CarbonTabSwipeNavigation()
        tabSwipe.createWithRootViewController(self, tabNames: names, tintColor: UIColor.redColor(), delegate: self)
        tabSwipe.setNormalColor(UIColor.whiteColor())
        tabSwipe.setSelectedColor(UIColor.blueColor())

Somebody with the same error?

**Comment by ermalkaleci** [comment]
what are you returning at delegated method? be sure you are not returning
nil

**Comment by ijpe** [comment]
Thanks for the quick response, that was the problem, so you see only put more clear that you need to modify the delegate, as I was just testing it looked like such copy which the code documentation.

**Comment by ermalkaleci** [comment]
please don't forget to close the issue if you fixed it :)

**Comment by ijpe** [comment]
Sure, tks!
