### ISSUE TITLE
Error on iOS7

### ISSUE THREAD

**Issue by prsolucoes** [ermalkaleci/CarbonKit#23]
Hi,

I have a problem on iOS7 only with my customers. Im receiving the error that is a bug on iOS7 and it is a common error but i tried without success solve it.

- http://javahow.net/questions/29182505/uitableviewcontroller-programmatically-autolayout-bug-on-ios-7
- http://stackoverflow.com/questions/12610783/auto-layout-still-required-after-executing-layoutsubviews-with-uitableviewcel

Can you help me?

**Comment by ermalkaleci** [comment]
What's the problem with the library?

**Comment by prsolucoes** [comment]
It crash the app when running on iOS7.
I'm dont using autolayout or interface builder and when i use ths library on iOS7 it crash with the errors that i show on link, is the same problem.
But on iOS8 it is working.

**Comment by prsolucoes** [comment]
I did made i simple sample of the problem:

https://github.com/prsolucoes/CarbonKitError

**Comment by prsolucoes** [comment]
The error happens on line:

- (void)didMoveToSuperview {
        ....
	[self setTranslatesAutoresizingMaskIntoConstraints:NO];
        ....
}

If you comment, it dont crash, but the view is not centralized.

**Comment by ermalkaleci** [comment]
Library require auto-layout, anyway I will check what I can do.

**Comment by prsolucoes** [comment]
I had added a README file on my sample repository to you see. Please, help me with this :(

**Comment by ermalkaleci** [comment]
You can not add CarbonSwipeRefresh as subview of tableView.
You need to add it on tableView container, like in the example

**Comment by ermalkaleci** [comment]
```objective-c
#import "ViewController.h"

@interface ViewController ()
{
    UITableView *tableView;
}

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    self.title = @"CarbonKit - Error - iOS7";
    
    tableView = [[UITableView alloc] initWithFrame:self.view.frame style:UITableViewStylePlain];
    [self.view addSubview:tableView];
    
    [self enablePullToRefresh];
}

- (void)enablePullToRefresh
{
    self.refresh = [[CarbonSwipeRefresh alloc] initWithScrollView:tableView];
    [self.refresh setMarginTop:64];
    [self.view addSubview:self.refresh];
    [self.refresh addTarget:self action:@selector(pullToRefresh:) forControlEvents:UIControlEventValueChanged];
}

- (void)pullToRefresh:(id)sender
{
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [self.refresh endRefreshing];
    });
}

@end
```

**Comment by ermalkaleci** [comment]
CarbonSwipeRefresh can't be child of tableView. It must be child of tableview parent. You need to add a tableView inside a viewController not directly in UITableViewController
this is the header or your example:
```objective-c

#import <UIKit/UIKit.h>
#import <CarbonKit/CarbonKit.h>

@interface ViewController : UIViewController

@property (nonatomic, retain) CarbonSwipeRefresh *refresh;

- (void)enablePullToRefresh;
- (void)pullToRefresh:(id)sender;

@end
```

**Comment by prsolucoes** [comment]
Ok, i have made the correction on project. It is working now, but i need put the code

```objective-c
if ([self respondsToSelector:@selector(edgesForExtendedLayout)])
{
    self.edgesForExtendedLayout = UIRectEdgeNone;
}
```

I need it?

**Comment by ermalkaleci** [comment]
I closed this issue
