### ISSUE TITLE
iOS 13.0 issue - selected tab background color is white by default nd can't able to change nd it's working properly in 12.1 or lower version..

### ISSUE THREAD

**Issue by KrupaDetroja** [ermalkaleci/CarbonKit#231]
This is 13.0 view

![ios_13 0](https://user-images.githubusercontent.com/30314359/60179988-ad08b700-983c-11e9-8ea8-d4696ba2e269.png)

This is 12.1 view

![iOS_12 1](https://user-images.githubusercontent.com/30314359/60180009-b5f98880-983c-11e9-9309-6c16d9016c14.png)

**Comment by marcinmierzejewski1024** [comment]
I have the same problem. My guess it's something with iOS 13 motives because when I changed 
carbonTabSwipeNavigation.toolbar.barStyle to UIBarStyleBlack (UIBarStyleBlackOpaque,UIBarStyleBlackTranslucent is depracated now), active tab background has changed from white to gray.

**Comment by ermalkaleci** [comment]
Fixing it...

**Comment by ermalkaleci** [comment]
@marcinmierzejewski1024 @KrupaDetroja fixed. v2.3.0

**Comment by KrupaDetroja** [comment]
> @marcinmierzejewski1024 @KrupaDetroja fixed. v2.3.0

Thank you!!!
