### ISSUE TITLE
iOS 13 Crash and just find issues.Please repair it as soon as possible.

### ISSUE THREAD

**Issue by jcg9487** [ermalkaleci/CarbonKit#240]
pageViewController setViewControllers need add to main queue.

__weak typeof(self) weakSelf = self;
    dispatch_async(dispatch_get_main_queue(), ^{
        [weakSelf.pageViewController setViewControllers:@[ viewController ]
         direction:animateDirection
          animated:animate
        completion:animateCompletionBlock];
    });

**Comment by emelyanovkirill** [comment]
Thanks, it helped me)
I had a fatal error for iOS 13:
 *** Assertion failure in UITraitCollection * _Nonnull _UIGetCurrentFallbackTraitCollection(void)(), /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3899.13.13/_UIFallbackEnvironment.m:91
error: Execution was interrupted, reason: breakpoint 1.1.
The process has been returned to the state before expression evaluation.
