### ISSUE TITLE
iOS 13 Crash and just find issues.Please repair it as soon as possible.

### ISSUE THREAD

**Issue by gaojlieMan** [ermalkaleci/CarbonKit#241]
iOS 13 Crash and just find issues.Please repair it as soon as possible.

**Comment by prakashRavi1990** [comment]
Hi,

Please find the crash details here.

*** Terminating app due to **uncaught exception** 'NSInternalInconsistencyException', reason: '<#Mycontroller#: 0x7fb2904a7e70> **returned nil from -traitCollection, which is not allowed.'**

This is happening when I am initialising the controller,

let carbonTabSwipeNavigation = CarbonTabSwipeNavigation(items: serviceSegmentTypes, delegate: self)

@gaojlieMan : You got the same? or Different?

**Comment by gaojlieMan** [comment]
the same with you.How Should I solve the problem？



------------------ 原始邮件 ------------------
发件人: "prakashRavi1990"<notifications@github.com>; 
发送时间: 2019年9月24日(星期二) 下午2:33
收件人: "ermalkaleci/CarbonKit"<CarbonKit@noreply.github.com>; 
抄送: "ｘ噺嫙ぁ侓"<401633128@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ermalkaleci/CarbonKit] iOS 13 Crash and just find issues.Pleaserepair it as soon as possible. (#241)




Hi,
 
Please find the crash details here.
 
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<#Mycontroller#: 0x7fb2904a7e70> returned nil from -traitCollection, which is not allowed.'
 
This is happening when I am initialising the controller,
 
let carbonTabSwipeNavigation = CarbonTabSwipeNavigation(items: serviceSegmentTypes, delegate: self)
 
@gaojlieMan : You got the same? or Different?

**Comment by ermalkaleci** [comment]
@prakashRavi1990 @gaojlieMan checkout example project. if it works ok then your problem is somewhere else

**Comment by gaojlieMan** [comment]
019-09-24 15:22:02.889176+0800 CarbonKitExample[5993:3225422] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<ViewControllerOne: 0x10532b2b0> returned nil from -traitCollection, which is not allowed.' OC demo crash is the same with my  project crash,How can solve it?




------------------ 原始邮件 ------------------
发件人: "Ermal Kaleci"<notifications@github.com>; 
发送时间: 2019年9月24日(星期二) 下午3:12
收件人: "ermalkaleci/CarbonKit"<CarbonKit@noreply.github.com>; 
抄送: "ｘ噺嫙ぁ侓"<401633128@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ermalkaleci/CarbonKit] iOS 13 Crash and just find issues.Pleaserepair it as soon as possible. (#241)




@prakashRavi1990 @gaojlieMan checkout example project. if it works ok then your problem is somewhere else

**Comment by prakashRavi1990** [comment]
The thing is when we try to access the UIElement in the initial loading view controller the following issue occurs 

Example: 
i am having search bar in the FirstViewController. While try to access the search bar like 

**searchBar.searchBarStyle = .minimal**

I am getting ***** Assertion failure in UITraitCollection * _Nonnull _UIGetCurrentFallbackTraitCollection(void)(), /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3899.13.13/_UIFallbackEnvironment.m:91**

The sad part is in Xcode 11 only I am facing this issue. All the other view controllers are working fine. The one with CarbonKit is not working. 

@ermalkaleci @gaojlieMan please let me know if you find any solution to this.

**Comment by gaojlieMan** [comment]
How can I slove it ?Can you help me



------------------ 原始邮件 ------------------
发件人: "prakashRavi1990"; 
发送时间: 2019年9月24日(星期二) 下午3:45
收件人: "ermalkaleci/CarbonKit";
抄送: "gaojlieMan"<401633128@qq.com>;"Mention";
主题: Re: [ermalkaleci/CarbonKit] iOS 13 Crash and just find issues.Pleaserepair it as soon as possible. (#241)




The thing is when we try to access the UIElement in the initial loading view controller the following issue occurs
 
Example:
 i am having search bar in the FirstViewController. While try to access the search bar like
 
searchBar.searchBarStyle = .minimal
 
I am getting ***** Assertion failure in UITraitCollection * _Nonnull _UIGetCurrentFallbackTraitCollection(void)(), /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3899.13.13/_UIFallbackEnvironment.m:91**
 
The sad part is in Xcode 11 only I am facing this issue. All the other view controllers are working fine. The one with CarbonKit is not working.
 
@ermalkaleci @gaojlieMan please let me know if you find any solution to this.
 
&mdash;

**Comment by gaojlieMan** [comment]
How can run your demo that can run no  problem



------------------ 原始邮件 ------------------
发件人: "prakashRavi1990"<notifications@github.com>; 
发送时间: 2019年9月24日(星期二) 下午3:45
收件人: "ermalkaleci/CarbonKit"<CarbonKit@noreply.github.com>; 
抄送: "ｘ噺嫙ぁ侓"<401633128@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ermalkaleci/CarbonKit] iOS 13 Crash and just find issues.Pleaserepair it as soon as possible. (#241)




The thing is when we try to access the UIElement in the initial loading view controller the following issue occurs
 
Example:
 i am having search bar in the FirstViewController. While try to access the search bar like
 
searchBar.searchBarStyle = .minimal
 
I am getting ***** Assertion failure in UITraitCollection * _Nonnull _UIGetCurrentFallbackTraitCollection(void)(), /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore_Sim/UIKit-3899.13.13/_UIFallbackEnvironment.m:91**
 
The sad part is in Xcode 11 only I am facing this issue. All the other view controllers are working fine. The one with CarbonKit is not working.
 
@ermalkaleci @gaojlieMan please let me know if you find any solution to this.

**Comment by gaojlieMan** [comment]
2019-09-24 15:22:02.889176+0800 CarbonKitExample[5993:3225422] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<ViewControllerOne: 0x10532b2b0> returned nil from -traitCollection, which is not allowed.' Your demo crash the same with my project,How can I run your demo with no crash,I hope you can solve it in your demo,Thanks.




------------------ 原始邮件 ------------------
发件人: "Ermal Kaleci"<notifications@github.com>; 
发送时间: 2019年9月24日(星期二) 下午3:12
收件人: "ermalkaleci/CarbonKit"<CarbonKit@noreply.github.com>; 
抄送: "ｘ噺嫙ぁ侓"<401633128@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ermalkaleci/CarbonKit] iOS 13 Crash and just find issues.Pleaserepair it as soon as possible. (#241)




@prakashRavi1990 @gaojlieMan checkout example project. if it works ok then your problem is somewhere else

**Comment by phungvantung** [comment]
![Screen Shot 2019-09-24 at 3 13 38 PM](https://user-images.githubusercontent.com/22878356/65494767-a3e0c200-dedf-11e9-93ce-d4f4d511e6b6.png)

**Comment by phungvantung** [comment]
same bug in your example project :(

**Comment by ermalkaleci** [comment]
Try swift one

**Comment by gaojlieMan** [comment]
Yes,the same with my.but I do not know how can I slove it




------------------ 原始邮件 ------------------
发件人: "Phùng V&#x103;n Tùng"<notifications@github.com>; 
发送时间: 2019年9月24日(星期二) 下午4:26
收件人: "ermalkaleci/CarbonKit"<CarbonKit@noreply.github.com>; 
抄送: "ｘ噺嫙ぁ侓"<401633128@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ermalkaleci/CarbonKit] iOS 13 Crash and just find issues.Pleaserepair it as soon as possible. (#241)




same bug in your example project :(

**Comment by gaojlieMan** [comment]
I want to use oc in my project,yan can solve it as soon as possible

**Comment by ermalkaleci** [comment]
Try to return empty view controller for each tap

**Comment by gaojlieMan** [comment]
if your oc demo you solve it,you can tell me as soon as possible

**Comment by ermalkaleci** [comment]
objc example fails because of [[CarbonSwipeRefresh alloc] init

**Comment by gaojlieMan** [comment]
Yes,the same with me.can you solve it and update to your git as soon as possible,thaks




------------------ 原始邮件 ------------------
发件人: "Ermal Kaleci"<notifications@github.com>; 
发送时间: 2019年9月24日(星期二) 下午4:47
收件人: "ermalkaleci/CarbonKit"<CarbonKit@noreply.github.com>; 
抄送: "ｘ噺嫙ぁ侓"<401633128@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ermalkaleci/CarbonKit] iOS 13 Crash and just find issues.Pleaserepair it as soon as possible. (#241)




objc example fails because of [[CarbonSwipeRefresh alloc] init

**Comment by gaojlieMan** [comment]
you can update your demo,I will download it,thanks

**Comment by ermalkaleci** [comment]
fixed

**Comment by gaojlieMan** [comment]
------------------ 原始邮件 ------------------
发件人: "prakashRavi1990"<notifications@github.com>; 
发送时间: 2019年9月24日(星期二) 下午5:01
收件人: "ermalkaleci/CarbonKit"<CarbonKit@noreply.github.com>; 
抄送: "ｘ噺嫙ぁ侓"<401633128@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ermalkaleci/CarbonKit] iOS 13 Crash and just find issues.Pleaserepair it as soon as possible. (#241)




Dear @ermalkaleci,
 
Please download the sample pod integrated swift application.
 
https://github.com/prakashRavi1990/SampleCarbonKit
 
Here we can see the crash.

**Comment by gaojlieMan** [comment]
Crash

**Comment by gaojlieMan** [comment]
picture in the email

**Comment by gaojlieMan** [comment]
you can update oc demo for me,thanks

**Comment by ermalkaleci** [comment]
v2.3.1 will be ready in a few min

**Comment by gaojlieMan** [comment]
Thanks




------------------ 原始邮件 ------------------
发件人: "Ermal Kaleci"<notifications@github.com>; 
发送时间: 2019年9月24日(星期二) 下午5:10
收件人: "ermalkaleci/CarbonKit"<CarbonKit@noreply.github.com>; 
抄送: "ｘ噺嫙ぁ侓"<401633128@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ermalkaleci/CarbonKit] iOS 13 Crash and just find issues.Pleaserepair it as soon as possible. (#241)




v2.3.1 will be ready in a few min

**Comment by etamluos** [comment]
thanksssss
