### ISSUE TITLE
Tab no more scrollable

### ISSUE THREAD

**Issue by sumit-ingewar** [ermalkaleci/CarbonKit#245]
Hi there ,

I am facing issue with tabs. Usually they are scrollable like in android but after updating to xcode 11 and on iOS 13 , the tabs are no more scrollable. Also I noticed the tabs looks also changed in latest OS update. Any help would be appreciated.

**Comment by StuckTitan682** [comment]
Any updates on this yet?

**Comment by roasted-almond** [comment]
Same issue here

**Comment by ozanofkeli** [comment]
```
- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)gestureRecognizer {
    return YES;
}
```

With iOS 13 UISegmentedControl is scrollable. That's why you guys should override gestureRecognizerShouldBegin method inside **CarbonTabSwipeSegmentedControl.m** file and return **YES**.

**Comment by sumit-ingewar** [comment]
Solutions provided by ozanofkeli works as expected
