### ISSUE TITLE
Change tab bar width

### ISSUE THREAD

**Issue by bubudrc** [ermalkaleci/CarbonKit#28]
Hi,

First of all, I want to say thanks for this tool.

My question is, how I can change script to have a segment like the attached screen.
![segment](https://cloud.githubusercontent.com/assets/619159/8120092/d45b777c-1071-11e5-8832-8d8c0e3e8b89.png)

![sgement_selected](https://cloud.githubusercontent.com/assets/619159/8120380/f5cb312e-1074-11e5-833f-b3737c13ad61.png)

Thanks

**Comment by ermalkaleci** [comment]
at CarbonTabSwipeNavigatio.m line 434, change +30 extra width

**Comment by bubudrc** [comment]
thanks man :D. That works !!!

**Comment by SriSamVictor** [comment]
Hi,

      First i need to do for set tab extra width for iphone and ipad. how can i do that in carbonkit? User interface idiom ipad is not support. how can i achieved it?

Thanks in advance
