### ISSUE TITLE
How to programmatically remove the swipe gestures 

### ISSUE THREAD

**Issue by zurceUABC** [ermalkaleci/CarbonKit#29]
I'm building an application that uses navigation drawers on both sides, I would love to have the ability to remove the swipe gesture when I'm on the first and the last tabs, I'm using delegates to detect the slides but I would like to programmatically enable or disable the scrolling of the tabs

Is there any way to do this?

**Comment by ermalkaleci** [comment]
This is not a good solution because you can't update pod

1. add this property at interface of CarbonTabSwipeNavigation.h
```objective-c
@property (nonatomic, weak) UIScrollView *scrollView;
```

2. get scrollView address at CarbonTabSwipeNavigation.m line 75
```objective-c
if ([v isKindOfClass:[UIScrollView class]]) {
    ((UIScrollView *)v).delegate = self;
    self.scrollView = (UIScrollView *)v; // get scrollView address
}
```
now you can control scrollView at rootViewController simply by tabSwipe.scrollView.scrollEnabled = NO

**Comment by dinhcuong1989** [comment]
im tried but its now working with your method

**Comment by ermalkaleci** [comment]
This was for version 1.x. We have a new version now.
You can access PageViewController using CarbonTabSwipeNavigation instance like this:
```objective-c
carbonTabSwipeNavigation.pageViewController
```
At your viewDidLoad block create a reference for the scrollview:
```objective-c
for (UIView *subView in carbonTabSwipeNavigation.pageViewController.view.subviews) {
    if ([subView isKindOfClass:[UIScrollView class]]) {
    // get scrollview reference here i.e: self.myScrollView = subView;
    }
}
```

then you can enable and disable scrolling using ie: 
```objective-c
self.myScrollView.scrollEnabled = NO
```

**Comment by dinhcuong1989** [comment]
im using swift and here is my code: 

   var items = NSArray()
    var carbonTabSwipeNavigation: CarbonTabSwipeNavigation = CarbonTabSwipeNavigation()
    var myScrollView : UIScrollView!

in viewDidLoad

items = ["Songs", "Albums"]
        carbonTabSwipeNavigation = CarbonTabSwipeNavigation(items: items as [AnyObject], delegate: self)
        carbonTabSwipeNavigation.insertIntoRootViewController(self)
        
        for subView: UIView in carbonTabSwipeNavigation.pageViewController.view.subviews {
            if (subView is UIScrollView) {
                // get scrollview reference here i.e: self.myScrollView = subView;
                self.myScrollView.addSubview(subView)
            }
        }

        
        self.style()

and style function

func style() {
        
        let color: UIColor =  UIColorFromRGB(0xe70353)
        let witdh = self.view.bounds.size.width / 2

        carbonTabSwipeNavigation.toolbar.translucent = false
        carbonTabSwipeNavigation.setIndicatorColor(color)
        carbonTabSwipeNavigation.setTabExtraWidth(0)
        carbonTabSwipeNavigation.carbonSegmentedControl!.setWidth(witdh, forSegmentAtIndex: 0)
        carbonTabSwipeNavigation.carbonSegmentedControl!.setWidth(witdh, forSegmentAtIndex: 1)
        
        carbonTabSwipeNavigation.setNormalColor(UIColor.blackColor().colorWithAlphaComponent(0.6))
        carbonTabSwipeNavigation.setSelectedColor(color, font: UIFont.boldSystemFontOfSize(14))

        self.myScrollView.scrollEnabled = false
    }

**Comment by ermalkaleci** [comment]
Of course you will get crash. You must assign subView as! UIScrollView as long as you are coding in Swift. I didn't said addSubview! You trying to add view into a nil. Just get the reference of scrollview to a weak instance.

**Comment by dinhcuong1989** [comment]
thanks, it worked :+1:

**Comment by satish8001** [comment]
hi  @dinhcuong1989  can u please post your code.
for this "You must assign subView as! UIScrollView"

**Comment by pawanline** [comment]
what is the meaning of  "v"  in the below line.

if ([v isKindOfClass:[UIScrollView class]]) {

**Comment by rhameed05** [comment]
Easiest way.
In your view controller :
 ` var swipeNavigation = CarbonTabSwipeNavigation()`

after you setup swipeNavigation, use code below

```
 for view in swipeNavigation.pageViewController.view.subviews {
            if let subView = view as? UIScrollView {
                subView.isScrollEnabled = false
            }
        }
```
