### ISSUE TITLE
Load every tabs at once

### ISSUE THREAD

**Issue by ValentinDenis** [ermalkaleci/CarbonKit#34]
Hi, I'd like to know if it's possible to load every tabs once, to navigate flawlessly between them (and not one by one when you switch them).
Thanks

**Comment by ermalkaleci** [comment]
Hi @ValentinDenis 

Yes it's possible.
If you call setCurrentTabIndex methods foreach tabs and then call again setCurrentTabIndex with index 0 or whatever.

Thanks

**Comment by ValentinDenis** [comment]
Works perfectly, thanks !

**Comment by ZoeVale** [comment]
Hi, excuse me but the solution
 for (int i = 1; i < numberOfTabs; i++)
    [tabSwipe setCurrentTabIndex:i];
[tabSwipe setCurrentTabIndex:0];
don't works .
Can you help me please ? It's don't call  TabIndex with index 0 but remains in TabIndex 2 (i Hanve e tab 0,1, 2 )
thank's in advance.

**Comment by ermalkaleci** [comment]
Hi @ZoeVale,
Ensure your are calling [tabSwipe setCurrentTabIndex:0]; outside the loop

**Comment by ZoeVale** [comment]
Hi, yes.
thi is my code:

I created a method  "careateTabSwipes" that i call in my viewDidLoad

- (void) createTabSwipes {
//tabSwipe
    _names = @[@"EVENTI", @"COUPON", @"STRUTTURE"];
    
    tabSwipe = [[CarbonTabSwipeNavigation alloc] createWithRootViewController:self
                                                                     tabNames:_names
                                                                    tintColor:[UIColor wadagoBlack]
                                                                     delegate:self];
    
    [ tabSwipe setSelectedColor:[UIColor whiteColor]
              andIndicatorColor:[UIColor wadagoGreen]
                           font:[UIFont boldSystemFontOfSize:14]];
    
    [tabSwipe setIndicatorHeight:4.f];
    [tabSwipe addShadow];
   
    for (int i = 1; i < 3; i++)
        [tabSwipe setCurrentTabIndex:i];
    
[tabSwipe setCurrentTabIndex:0];
    
}

**Comment by ermalkaleci** [comment]
Confirmed!
The last commit was for animation when click the tab. This cause the bug.
Do not use latest code. Use CocoaPods version

**Comment by ZoeVale** [comment]
Thank you man.
I have some problem to use CocoaPods can you tell me which version i can use please?

**Comment by ermalkaleci** [comment]
use the last release
https://github.com/ermalkaleci/CarbonKit/releases/tag/1.1.2

**Comment by ZoeVale** [comment]
I'm going to use this version tomorrow.
Thank you very much. ;-)
