### ISSUE TITLE
Slide/swipe animation when tab items are tapped.

### ISSUE THREAD

**Issue by aparna1591** [ermalkaleci/CarbonKit#35]
I would like to know how we can obtain a slide/swipe animation between the views when a tab item is tapped on. As of now it simply changes the view without animation when tapped.
Please help me out with this.
Thanks in advance!

**Comment by ermalkaleci** [comment]
Hi @aparna1591 
I have disabled animation for tab tapped because it cause problem in iOS 7, iOS 8 is fine.
I also want this feature and will see what I can do

**Comment by ermalkaleci** [comment]
Hey @aparna1591 
I found a way. Checkout the latest code :+1:

**Comment by aparna1591** [comment]
Will do, thanks a lot!

**Comment by aditya-s-iprogrammer** [comment]
I have a slider in my view if I try to swipe slider my carbon view is getting swiped and going to new view.  Is there any way to disable this swipe?
