### ISSUE TITLE
How to add a View in the bottom  of ViewController for use as bottom bar

### ISSUE THREAD

**Issue by subhash08** [ermalkaleci/CarbonKit#37]
i want to add a view in the bottom of viewcontroller, for use as BottomBar .
like in this pic
![screen shot 2015-08-28 at 4 53 29 pm](https://cloud.githubusercontent.com/assets/11552671/9545299/ccd6622a-4da5-11e5-8cd2-ad8591a0add8.png)

**Comment by subhash08** [comment]
i did it 
sorry for posting issue before do my best.

**Comment by gustavogervasio** [comment]
@subhash08 how?

**Comment by subhash08** [comment]
@gustavogervasio  
find `- (void)viewDidLayoutSubviews ` method in `CarbonTabSwipeNavigation.m` than
in following line

      	pageController.view.frame = CGRectMake(pageController.view.frame.origin.x, pageController.view.frame.origin.y, self.view.bounds.size.width, pageController.view.frame.size.height-60);
change the height of pageController, In my case I just want to add a view with height of 60 then I then i change height  `pageController.view.frame.size.height-60` then after I add my view and other objects.
Hope it may helps.
Happy coding.

**Comment by gustavogervasio** [comment]
thanks... :+1:

**Comment by dewanshuBuzzyears** [comment]
override func viewDidLayoutSubviews() {
        carbonTabSwipeNavigation?.view.frame = CGRect(x:0.0,y:0.0,width:screenWidth,height:screenHeight-60)
    }

**Comment by dewanshuBuzzyears** [comment]
override func viewDidLayoutSubviews() {
      
        view.addConstraint(NSLayoutConstraint(item: carbonTabSwipeNavigation!.view, attribute: .top, relatedBy: .equal, toItem: self.topLayoutGuide, attribute: .bottom, multiplier: 1, constant: 0))
        
        view.addConstraint(NSLayoutConstraint(item: carbonTabSwipeNavigation!.view, attribute: .bottom, relatedBy: .equal, toItem: self.bottomLayoutGuide, attribute: .top, multiplier: 1, constant: -60))
        
        view.addConstraint(NSLayoutConstraint(item: carbonTabSwipeNavigation!.view, attribute: .leading, relatedBy: .equal, toItem: self.view, attribute: .leading, multiplier: 1, constant: 0))
        
        view.addConstraint(NSLayoutConstraint(item: carbonTabSwipeNavigation!.view, attribute: .trailing, relatedBy: .equal, toItem: self.view, attribute: .trailing, multiplier: 1, constant: 0))
        
        
    }
