### ISSUE TITLE
ScrollView over my controller- not a bug-

### ISSUE THREAD

**Issue by ayashi38** [ermalkaleci/CarbonKit#39]
Hello. 
I'am quite new in developing and having fun discovering stuff . Was wondering if it is possible to have the scrollView over my content and not on top. 

I put an image on top over the statusbar (got some pain with this bar sometimes) and want to have some transparancy on the scrollview in order to put it over my imageview(and not having the image view under the scroll view and having a white status bar)

for now, gonna try to overload (don't know if it is the correct word in swift) your code and maybe play with offset. 
i guess I have to play with constraint... but not used to write it in the code :D

Thanks anyway

**Comment by ermalkaleci** [comment]
Hello @ayashi38 
I'm not understanding. Please can you give any example or screenshot?

**Comment by batical** [comment]
thanks for your quick answer. image is better than word (with my bad english)

I had  this on a single page (image under transparant status bar)
![img_6438](https://cloud.githubusercontent.com/assets/7248073/9982591/dbccfda4-5fe1-11e5-8d11-0d935d47add6.jpeg)


now i got 
![img_7338](https://cloud.githubusercontent.com/assets/7248073/9982596/f8815738-5fe1-11e5-9f54-a20639192b78.jpeg)


I was thinking yesterday with a bottle of red wine (am french :p) to play with your  code for fun and learn :)

Btw, it is not for real project, just having fun discovering ios dev and looking on some nice example

**Comment by ermalkaleci** [comment]
Nice :)
I am working on a new version that support more customisation.
Current version have the content after tabBar not above. The next version will allow the developers to add tabBar also at the bottom.
Cheers :wine_glass:

**Comment by batical** [comment]
nice :) waiting to analyze you new code :D

**Comment by ayashi38** [comment]
Forgot to close
