### ISSUE TITLE
Include with other controls in UIViewController

### ISSUE THREAD

**Issue by khunshan** [ermalkaleci/CarbonKit#40]
It looks not possible to use CarbonTabSwipeNavigation in an already UIViewController incase if we want to have a banner, header or simply any other UIView above Tabs. Its because CarbonTabSwipeNavigation inherits UIViewController which I believe restricts itself to be used as a part of some UIViewController beside other controls of UI instead it is a full fledge UIViewController.

Is there a way to use CarbonTabSwipeNavigation inside as a control in UIViewController? Like this:
![05-1dashboard-accounts](https://cloud.githubusercontent.com/assets/1384695/10122435/b269643c-6533-11e5-9ea2-7a2cc7cde64f.jpg)

**Comment by ermalkaleci** [comment]
Hello @khunshan,
Yes it is a way. In next version this will be much easy.
Anyway if you create a new ViewController (A) for below view (CarbonTabSwipeNavigation) and use this (A) as rootViewController for CarbonTabSwipe and then addSubview A.view to rootView.

```objective-c

@interface HomeViewController () <CarbonTabSwipeDelegate>
{
	UIViewController *A;
}
@end 

@implementation HomeViewController

- (void)viewDidLoad {
	[super viewDidLoad];
	
	A = [[UIViewController alloc] init];
	A.view.frame = CGRectMake(0, 200, 320, 300); // just creating a frame
	[self.view addSubview:A.view];
	
	NSArray *names = @[@"ONE", @"TWO", @"THREE", @"FOUR", @"FIVE", @"SIX", @"SEVEN", @"EIGHT", @"NINE", @"TEN"];
	UIColor *color = [UIColor white];
	tabSwipe = [[CarbonTabSwipeNavigation alloc] createWithRootViewController:A tabNames:names tintColor:color delegate:self];
}
@end
```

**Comment by ancheng1114** [comment]
Thanks , it's working nice.

**Comment by khunshan** [comment]
I missed it. However. I am glad it does work now.

On Mon, Oct 26, 2015 at 12:55 PM, ancheng <notifications@github.com> wrote:

> Thanks , it's working nice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ermalkaleci/CarbonKit/issues/40#issuecomment-151052474>
> .
>



-- 

*Khunshan S. Ahmad*

**Comment by JigneshParekh7165** [comment]
My Header Height is 64 how can i set CarbonTabSwipeNavigation  start from 64....Plz Help Me...

class MessgeVC: UIViewController,CarbonTabSwipeNavigationDelegate
{
    
    var items = NSArray()
    var carbonTabSwipeNavigation: CarbonTabSwipeNavigation = CarbonTabSwipeNavigation()

    override func viewDidLoad() 
{
        super.viewDidLoad()

        self.title = "Message"
        items = ["Agent", "Comment"]
        
        carbonTabSwipeNavigation = CarbonTabSwipeNavigation(items: items as [AnyObject], delegate: self)
        carbonTabSwipeNavigation.insertIntoRootViewController(self)
        carbonTabSwipeNavigation.setNormalColor(UIColor(white: 1, alpha: 0.8))
        carbonTabSwipeNavigation.setSelectedColor(UIColor.whiteColor())
        self.style()
}


it started from (0,0,320,30) how can i solve this issue???

![chat_1024](https://cloud.githubusercontent.com/assets/19408195/15321897/14d4ae6c-1c57-11e6-8674-47121c5f03b3.png)

**Comment by ermalkaleci** [comment]
use `[carbonTabSwipeNavigation insertIntoRootViewController:self andTargetView:yourView];`

**Comment by JigneshParekh7165** [comment]
class MessgeVC: UIViewController,CarbonTabSwipeNavigationDelegate

{



    var items = NSArray()

    var carbonTabSwipeNavigation: CarbonTabSwipeNavigation =
CarbonTabSwipeNavigation()

    var a: UIViewController!


    override func viewDidLoad() {

        super.viewDidLoad()



        a.view.frame = CGRectMake(0, 64, 320, 30)

        self.view.addSubview(a.view)


        self.title = "Message"

        items = ["Agent", "Comment"]



        carbonTabSwipeNavigation = CarbonTabSwipeNavigation(items: items as
[AnyObject], delegate: self)

        carbonTabSwipeNavigation.insertIntoRootViewController(self,
andTargetView: a.view)



I had place this code but its not working what can i do for
carbonTabSwipeNavigation Started from 0,64,320,30....Help Me Bro....

**Comment by ermalkaleci** [comment]
create a UIView not UIViewController. you can do it from storyboard and create an IBOutlet
