### ISSUE TITLE
CarbonKit in Swift

### ISSUE THREAD

**Issue by JannyKul** [ermalkaleci/CarbonKit#41]
Selamlar Ermal Abi, thank you so much for the library, the functionality here is exactly what I was looking for. However, I am struggling to get it working in swift using the bridging file route. I have started by trying to create a very simple version of your example document to try and figure out where the issue is however this hasn't helped. Everything compiles and builds fine but the error is thrown during run time.

The code I am using is below and where the error is thrown is shown below. From what I can tell the line throwing the error is:
tabSwipe.createWithRootViewController(self, tabNames: names, tintColor: color, delegate: self)

Any help would be greatly appreciated. Thank you.

This is my code:
![screen shot 2015-10-03 at 13 51 50](https://cloud.githubusercontent.com/assets/14953265/10262980/f64fc35c-69d5-11e5-9ad6-68545e9c4859.png)

This is where the error is being thrown within the library:
![screen shot 2015-10-03 at 13 54 10](https://cloud.githubusercontent.com/assets/14953265/10262999/53d77c5e-69d6-11e5-88f1-7bc36353f1a2.png)
![screen shot 2015-10-03 at 13 54 37](https://cloud.githubusercontent.com/assets/14953265/10263002/57f087e0-69d6-11e5-8931-2a65886e2494.png)

**Comment by ermalkaleci** [comment]
Hi
Check delegate function. You are returning nil instead of a viewcontroller.
Btw I'm not Turkish.

**Comment by JannyKul** [comment]
Thank you so much for your quick response! I'm terribly sorry but I don't think I quite understand, are you referring to the "delegate: self" part of the above code - I would have thought this is supposed to reference the HomeViewController? Apologies for my lack of understanding.

**Comment by ermalkaleci** [comment]
At delegate func tabSwipeNavigation
Make sure you are returning a viewController because you are trying to put
a nil instead of a viewController

**Comment by JannyKul** [comment]
yes perfect that worked, thank you so much for the help!

**Comment by alangonzalez93** [comment]
@JannyKul can you show me the swift code? i try to use it but i can't get it to work.

**Comment by JannyKul** [comment]
Of course, remind me of the issue or let me know what problem you're having? It works for me now

Sent from my iPhone
------------------------------

**Comment by alangonzalez93** [comment]
@JannyKul @ermalkaleci Hi guys, I could make this work on SWIFT. My question now is how to add constrains on the CarbonTabSwipeNavigation to adapt this on the different screens size.

**Comment by ermalkaleci** [comment]
Hi @alangonzalez93 
What is not working on Swift?

```swift
class ViewController: UIViewController, CarbonTabSwipeNavigationDelegate {

    // MARK: Override methods
    override func viewDidLoad() {
        super.viewDidLoad()
        let items = ["Features", "Products", "About"]
        let carbonTabSwipeNavigation = CarbonTabSwipeNavigation.init(items: items, delegate: self)
        carbonTabSwipeNavigation.insertIntoRootViewController(self)
    }

    func carbonTabSwipeNavigation(carbonTabSwipeNavigation: CarbonTabSwipeNavigation, viewControllerAtIndex index: UInt) -> UIViewController {
        // return viewController at index
    }
}
```

This method will insert into root view controller using top and bottomLayoutGuide anchors. 
```swift
 carbonTabSwipeNavigation.insertIntoRootViewController(self)
```

or you don't call this method and insert carbonTabSwipeNavigation view manually
```swift
[self.view addSubView:carbonTabSwipeNavigation.view];
```

then add constraints i.e:
```swift
"V:|carbonTabSwipeNavigation.view|"
"H:|carbonTabSwipeNavigation.view|"
```
