### ISSUE TITLE
Unsync indicator bar

### ISSUE THREAD

**Issue by wanbok** [ermalkaleci/CarbonKit#50]
When CarbonTabSwipeNavigation is added dynamically, there is no indicator.

**Comment by ermalkaleci** [comment]
Hey @wanbok 
I don't have time this week and will check it by next week :+1:

**Comment by ermalkaleci** [comment]
Hey @wanbok
I am not finding this issue.

**Comment by wanbok** [comment]
@ermalkaleci Oh, I was doing wrong. I'm sorry to make you confused. :cry:

**Comment by ermalkaleci** [comment]
@wanbok no problem :smile:
