### ISSUE TITLE
Programmatically change to a different tab?

### ISSUE THREAD

**Issue by CodingCharlie** [ermalkaleci/CarbonKit#52]
Is there a way to change the current tab programatically?

e.g. like using [self.tabBarController setSelectedIndex:1]; when you are using a tab bar controller

**Comment by ermalkaleci** [comment]
Yes there is. setCurrentTabIndex:

**Comment by CodingCharlie** [comment]
Thanks for getting back to me.

Do you have an example of this? Do i need to create an instance of the HomeViewController or CarbonTabSwipeNavigation in the view controller that i'm calling it from?

**Comment by ermalkaleci** [comment]
'''objective-c
CarbonTabSwipeNavigation *carbonTabSwipeNavigation = 
    [[CarbonTabSwipeNavigation alloc] initWithItems:items delegate:self];
    [carbonTabSwipeNavigation insertIntoRootViewController:self];
[carbonTabSwipeNavigation setCurrentTabIndex:2];
'''

**Comment by Narendratha** [comment]
how to set image color in segment controller carbonkit

**Comment by ermalkaleci** [comment]
Please check out the example or public methods before asking.
```objective-c
[carbonTabSwipeNavigation setNormalColor:color];
[carbonTabSwipeNavigation setSelectedColor:color];
```

**Comment by xplorerakesh** [comment]
hello can i call Move to carbonTabSwipeNavigation from Index : 0 to Index:1.. 
Example : Using Carbon kit with 3 UIviewcontroller . when user click UIbutton at ViewController One  so i want my carbonTabSwipeNavigation move to Index :1 and uiViewController Two Will Appear on the screen .. If its possible , so share code with me ..Thanks :)

**Comment by hariios123** [comment]
xplorerakesh hi, you got answer for your issue in carbonkit..?

hello can i call Move to carbonTabSwipeNavigation from Index : 0 to Index:1..
Example : Using Carbon kit with 3 UIviewcontroller . when user click UIbutton at ViewController One so i want my carbonTabSwipeNavigation move to Index :1 and uiViewController Two Will Appear on the screen .. If its possible , so share code with me ..Thanks :)

**Comment by GaneshKumarSelvam** [comment]
Do any one got solution for this?
