### ISSUE TITLE
Custom navigationbar

### ISSUE THREAD

**Issue by mohsinalimat** [ermalkaleci/CarbonKit#53]
Hello,

i face one issue when i hide navigationbar hidden and i create custom view of at top than i want to show your controller?

Thanks,
Mohsinali

**Comment by ermalkaleci** [comment]
Hi @mohsinalimat 
if you use insertIntoRootViewController, library use topLayoutGuide and bottomLayoutGuide. Use insertIntoRootViewController andTargetView
