### ISSUE TITLE
CarbonTabSwipeNavigation : How to set a particular index as the initial viewcontroller?(say index : 2)

### ISSUE THREAD

**Issue by abhimuralidharan** [ermalkaleci/CarbonKit#54]
Your code is awesome.But how to set the second  index as the initial view?Thanks.

**Comment by abhimuralidharan** [comment]
Solved the issue:

Added an extra parameter "initialIndex" while initialising the `CarbonTabSwipeNavigation`,and this initialIndex is used to set the selectedIndex property in the `CarbonTabSwipeNavigation.m` file

- (instancetype)initWithItems:(nullable NSArray *)items
					  toolBar:(nonnull UIToolbar *)toolBar
					 delegate:(nonnull id)target initialIndex:(NSUInteger)initialIndex;

**Comment by ermalkaleci** [comment]
You can use also setCurrentIndex method. Anyway you hacked by yourself :+1:

**Comment by jonysingla** [comment]
There is some spacing when used iPhone 6. How to resolve this.


![screen shot 2017-10-28 at 11 20 20 am](https://user-images.githubusercontent.com/7313159/32131695-522bcc20-bbd2-11e7-80dc-bb2ce4ac8486.png)

**Comment by hariios123** [comment]
Hi i am using carbonkit in my project it is possible to highlight particular tabbar without moving to that tabbar.
For example:
              If i scroll in first tab after some scroll  height is it is possible to highlight second tabbar without moving to that tabbar index page.
