### ISSUE TITLE
Issue with RTL (iOS 9.x) (The indicator resizes to the tab Before next not after and More) ...

### ISSUE THREAD

**Issue by shehabic** [ermalkaleci/CarbonKit#55]
There's an issue when displaying the tabs in RTL, if you start swiping the library starts Highlighting the TAB on the other direction, and the indicator keeps resizing to the size of the tab opposite to the direction of swiping.

e.g. 
In LTR:
```
|  VERY WIDE TAB 1 | TAB 2 | LONG TAB 3 |
                   --------                            
```
Swiping in this direction ------>

When swiping from TAB 2 to to TAB 3, the indicator keeps resizing to TAB 3's size until you lift your finger and it stops smoothly, also during the swipe TAB 3, keeps getting the highlighted color until it transitions completely. 

now  in RTL:
```
| LONG TAB 3 | TAB 2 | VERY WIDE TAB 1 |
             --------
```
<--------- Swiping in this direction

When Swiping again from TAB 2 to TAB3 the following happens:
1-While swiping the indicator keeps resizing to fit the width of "TAB 1" not TAB 3, and also TAB 1 keeps getting the highlight color, 
2-Once you lift your finger the indicator corrects itself to the size of TAB3 and the highlight is set on TAB 3, (and this happens suddenly so it looks so flickering).

**Comment by shehabic** [comment]
Also notice something for iOS with LTR,  everything is flipped from LTR to RTL but the actually X-Axis still measures from 0 (on the far left) to the max on (the far right), 
for example of set text to align left, it'll align right,   if you set constraint left: 10 pt,  it'll be constraint right 10 pt. 
but if you measure the position of item standing at the far left, it'll be 0, while on the right it'll be something like 300... 

I'm not expert, but I thought that info might help, will also try to debug the code locally and see what's happening exactly.

**Comment by shehabic** [comment]
Notice: this issue Affects iOS 9 only, in iOS 8 the library is always displayed LTR

**Comment by ermalkaleci** [comment]
hey @shehabic 
please can you post any screenshot? I will see this issues asap

**Comment by shehabic** [comment]
I will upload a video shortly and share the link here

**Comment by shehabic** [comment]
@ermalkaleci here it is: https://www.youtube.com/watch?v=7YqM54Z2fDU

**Comment by shehabic** [comment]
I added this small piece of code to help me understand what's happening with RTL on ios 9+ :
```
        bool RTL = [UIApplication sharedApplication].userInterfaceLayoutDirection == UIUserInterfaceLayoutDirectionRightToLeft;       
        NSLog(@"offsetX: %f, SegmentWidth: %f, ScrollViewWidth: %f", offset.x, segmentedWidth, scrollViewWidth);
        NSLog(@"is Right to left: %@", RTL ? @"yes" : @"no");
```
around here:
https://github.com/ermalkaleci/CarbonKit/blob/master/CarbonKit/CarbonTabSwipeNavigation.m#L308

The issue I found is a bit complicated, the indexes of tabs are somehow flipped on RTL, also the condition of ScrollX vs Width is flipped, but only on iOS 9, so I found that the hack I did was a bit messy and doesn't qualify enough to be a quality PR.

**Comment by ermalkaleci** [comment]
@shehabic so on iOS 8, it works fine?

**Comment by shehabic** [comment]
Yes because the lib is displayed LTR on iOS 8
But if you use the condition above, RTL will be true, though the lib is showing LTR but the rest of the UI is RTL

**Comment by ermalkaleci** [comment]
I think I fixed it
![carbontabswipenavigationrtl](https://cloud.githubusercontent.com/assets/3055344/12374717/fc6570a8-bca4-11e5-94ed-306da98d8649.gif)

**Comment by ermalkaleci** [comment]
@shehabic can you try and let me know?
add this to your Podfile
```ruby
pod 'CarbonKit', :git => 'https://github.com/ermalkaleci/CarbonKit.git', :commit => 'ae5830e'
```
```bash
pod update CarbonKit
```

**Comment by shehabic** [comment]
:+1: works perfectly, thanks, and keep up the great work, I think this lib. definitely deserves more Stars.

**Comment by ermalkaleci** [comment]
@shehabic I am deploying version 2.1.1
Make sure to update podfile
