### ISSUE TITLE
TabExtraWidth is applied multiple times

### ISSUE THREAD

**Issue by omeryarn** [ermalkaleci/CarbonKit#56]
When setting TabExtraWidth, the extra width is applied multiple times (on each redraw) which causes the tabs to grow endlessly.

_My suggestion:_
On CarbonTabSwipeSegmentedControl.m:77 add a flag which indicates if the extra width has been added already.

**Comment by Mohamed-Shehab** [comment]
+1
Yes, I'm facing the same issue

**Comment by omeryarn** [comment]
Added a pull request that fixes this issue

**Comment by ermalkaleci** [comment]
Hi @omeryarn 
This way extraWidth will be static

**Comment by omeryarn** [comment]
When isn't it static?
I'm always setting a static value like this:
[carbonTabSwipeNavigation setTabExtraWidth:30];

**Comment by ermalkaleci** [comment]
I will fix it now

**Comment by ermalkaleci** [comment]
Sorry guys I have been to busy
