### ISSUE TITLE
App hang when flipped too fast between tabs

### ISSUE THREAD

**Issue by letien91** [ermalkaleci/CarbonKit#58]
I used example 1 and added 4 tabs into segment. Then I flipped quite fast between tabs. The example was hung.
I tested on Ipad Air iOS 9.2

**Comment by ermalkaleci** [comment]
@letien91 
are you using latest version and please you upload any video or GIF?

**Comment by chiragpipaliya** [comment]
[Corbonkit Video.zip](https://github.com/ermalkaleci/CarbonKit/files/229735/Corbonkit.Video.zip)
we implement carbonkit with 4 tabs in iPhone and iPad but in both are hang when we swipe. app is also hang when we swipe/flipped in normal speed. you can see this video we attach this app video in ipad.
