### ISSUE TITLE
How to fix duplicate

### ISSUE THREAD

**Issue by TrungVu37** [ermalkaleci/CarbonKit#60]
I have 4 major tabs in each tab, I insert 2 or 3 small tab , and then I started flip, the small tabs tabs not be made that big jump over the right tab . how to fix this

Project demo: https://www.dropbox.com/s/mmq5umaxq6r6ka5/PageMenuDemoStoryboard.zip?dl=0

**Comment by ermalkaleci** [comment]
@TrungVu37 Fixed

**Comment by TrungVu37** [comment]
Hi @ermalkaleci, 
I mean, if you flipped the constant small tabs or sub tab will not be able to slip through the tab father , only if you stop flip small tab, it will roll dad , I have made ​​this example to see it open the them out of view

**Comment by ermalkaleci** [comment]
@TrungVu37 
Please can you explain it more clear. The example project you have uploaded on DropBox works fine.
I'm not understanding what you mean
