### ISSUE TITLE
Tab Bar Color

### ISSUE THREAD

**Issue by pkgundam** [ermalkaleci/CarbonKit#62]
Hi, thank you for the amazing library?
This is not an issue.
Can you please tell me how do I make the navigation bar and the tab bar control which has all the swipe options the same color, I went through the code but could not find how to set the color for tab bar.

Like this.
https://s3.amazonaws.com/cocoacontrols_production/uploads/control_image/image/6057/iOS_Simulator_Screen_Shot_28_Mar_2015_20.42.34.png

Thank you for your help.

**Comment by pkgundam** [comment]
sorry, I meant to post it on the Swift Github Page, I will close this and post it there.

**Comment by ermalkaleci** [comment]
@pkgundam 
`carbonTabSwipeNavigation.toolbar.barTintColor = color;`

**Comment by pkgundam** [comment]
thank you very much. Appreciate it.
