### ISSUE TITLE
[Support] How to get index when tap on current tab?

### ISSUE THREAD

**Issue by letien91** [ermalkaleci/CarbonKit#65]
Thanks

**Comment by ermalkaleci** [comment]
@letien91 using delegate method or `carbonTabSwipeNavigation.currentTabIndex`

**Comment by letien91** [comment]
I added this code:
`#pragma mark - Touch
- (void)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event {
    [super touchesBegan:touches withEvent:event];
}

- (void)touchesEnded:(NSSet *)touches withEvent:(UIEvent *)event {
    NSInteger previousSelectedSegmentIndex = self.selectedSegmentIndex;
    [super touchesEnded:touches withEvent:event];
    if (previousSelectedSegmentIndex == self.selectedSegmentIndex) {
        [[NSNotificationCenter defaultCenter] postNotificationName:@"LFCarbonTabSwipeSegmentedControl" object:nil];
    }
}`

**Comment by praveenkumar56060** [comment]
Hey @letien91 

Thanks for your piece of code. It works fine.
