### ISSUE TITLE
In width issue

### ISSUE THREAD

**Issue by mohsinalimat** [ermalkaleci/CarbonKit#67]
Hello,

suppose i mutable array one records then run the project with latest source code does not reflect in full width. Please refer attach image

![screen shot 2016-02-10 at 3 45 04 pm](https://cloud.githubusercontent.com/assets/973676/12944438/0d633be4-d00d-11e5-9c63-d6219e7af486.png)

**Comment by ermalkaleci** [comment]
I am sorry, I have no idea what you mean

**Comment by mohsinalimat** [comment]
hello,

attach image from your old source code records show perfectly but your latest source code does not show like as below image...

![screen shot 2016-02-11 at 10 51 36 am](https://cloud.githubusercontent.com/assets/973676/12969912/3c63d73c-d0ad-11e5-9137-c6030a69b456.png)

**Comment by ermalkaleci** [comment]
This feature is removed on version 2.0. You can this by setting the width of segment manually

**Comment by mohsinalimat** [comment]
ohhhh no

**Comment by ermalkaleci** [comment]
you can change the width just like this `[carbonTabSwipeNavigation.carbonSegmentedControl setWidth:80 forSegmentAtIndex:0];`

**Comment by mohsinalimat** [comment]
but you have add this functionality also.
