### ISSUE TITLE
Wrong scroll animation when using setCurrentTabIndex:

### ISSUE THREAD

**Issue by Macjon** [ermalkaleci/CarbonKit#68]
I have 10 pages and want to allow the user to go to the next screen with a button. So I set the current index with the method:
`[carbonTabSwipeNavigation setCurrentTabIndex:2];`
 
But when I go from tab 1 to 2 the scroll animation is from right to left and not from left to right.

**Comment by ermalkaleci** [comment]
@Macjon can you record your screen and post more info?

**Comment by ermalkaleci** [comment]
@Macjon  Thank you for reporting. Fixed
