### ISSUE TITLE
How Can I Add to Bottom

### ISSUE THREAD

**Issue by invisible66** [ermalkaleci/CarbonKit#7]
i want to add tab bar to bottom. How can i do this? Yani tab barı ekranın alt kısmına nasıl alırım? ;)

**Comment by ermalkaleci** [comment]
Hi,
sorry it is not an option yet. Try to customize yourself :-)
Please don't open an issue for questions "how to" and I am Albanian, not Turkish ;-)

**Comment by invisible66** [comment]
Your name like a Turhish name :) . Thanks your answer.

**Comment by ermalkaleci** [comment]
Memory from Ottoman Empire ;-)
Try to customize yourself. I you can't let me know and I will try as soon
as I can ;-)

**Comment by armanim** [comment]
@invisible66 
You can change the pageController.view.frame height on (void)viewDidLayoutSubviews function, and put the Tab Bar to root view.

**Comment by ermalkaleci** [comment]
Please, can you explain a little bit more because I am not understanding.

**Comment by armanim** [comment]
There is a bottom tab bar, which have 50px height, in my root view.
But it is not visible because of the swipe view (covered by swipe view). So I changed the swipe view`s frame height to 50px less than original. Then the bottom view become visible.
** Sorry for my poor English **
``` objective-c
- (void)viewDidLayoutSubviews {
	[super viewDidLayoutSubviews];
	
	UIView *tab = tabs[segmentController.selectedSegmentIndex];
	indicatorWidthConst.constant = tab.frame.size.width;
	indicatorLeftConst.constant = tab.frame.origin.x;
	
	// keep the page controller's width in sync
    // *** I have changed next line ***
	pageController.view.frame = CGRectMake(pageController.view.frame.origin.x, pageController.view.frame.origin.y, self.view.bounds.size.width, pageController.view.frame.size.height - 50);

	[self resizeTabs];
	[self fixOffset];
	[self.view layoutIfNeeded];
	
}
```
