### ISSUE TITLE
Error view when pushto viewcontroller then back

### ISSUE THREAD

**Issue by TrungVu37** [ermalkaleci/CarbonKit#75]
https://www.dropbox.com/s/1tb3dxv7dupil1x/IMG_0079.jpg?dl=0

**Comment by ermalkaleci** [comment]
There is an example project on this repo. Probably you are doing something wrong on your code

**Comment by TrungVu37** [comment]
No, i use project demo from you, can you check it https://www.dropbox.com/s/pxyaii1qs4lzgzg/CarbonKit-master.zip?dl=0

**Comment by ermalkaleci** [comment]
![Uploading Screen Shot 2016-03-08 at 10.28.40.png…]()
You are setting fixed width for each tab

**Comment by TrungVu37** [comment]
Yes, i'm doing this, because i don't want toolbar scroll left or right. How to fix width?

**Comment by ermalkaleci** [comment]
carbonTabSwipeNavigation.carbonSegmentedControl is subclass of UISegmentedControl
you can change the font:
```objective-c
id titleAttr = @{
    NSForegroundColorAttributeName : [self.tintColor colorWithAlphaComponent:0.8],
    NSFontAttributeName : [UIFont boldSystemFontOfSize:14]
};
[self setTitleTextAttributes:titleAttr forState:UIControlStateNormal];
```
