### ISSUE TITLE
Problems when using `hidesBarOnSwipe`

### ISSUE THREAD

**Issue by chika-kasymov** [ermalkaleci/CarbonKit#77]
I want to hide my `UINavigationBar` on scroll, so I set `self.navigationController.hidesBarOnSwipe = true`. Everything works fine when I use pure `UITableView`, but there are problems when using `UIViewController` with inserted `CarbonTabSwipeNavigation`.

When I changed your code in **CarbonTabSwipeNavigation.m** line 49 to: `NSString *verticalFormat = @"V:|[carbonTabSwipe][bottomLayoutGuide]";` instead of `NSString *verticalFormat = @"V:[topLayoutGuide][carbonTabSwipe][bottomLayoutGuide]";` it started working for one tabbed `UIViewController` only. For many it doesn't hide or show `UINavigationBar`.

**Comment by ermalkaleci** [comment]
how is this supposed to work if you break the constraints?

**Comment by ermalkaleci** [comment]
you can observe the scrollview and hide navigation manually. On the home view controller observe notification and on the child view controller post notification. Depending on the scroll direction post a notification for hiding or showing and on the home VC call hideNavigaiton or showNavigation

**Comment by chika-kasymov** [comment]
Ok, for now I will stop on variant of observing my `UITableView` with external library.
