### ISSUE TITLE
setCurrentTabIndex and then Swipe = weird behaviour

### ISSUE THREAD

**Issue by egruttner** [ermalkaleci/CarbonKit#83]
Hi...thank you for making this great library.
But I'm having some trouble with it:
1.- I do [carbonTabSwipeNavigation setCurrentTabIndex:self.idNav];
2.- The toolbar works right, moving to the new index
3.- If I touch the headers, everything works ok but...
4.- If I swipe, the pages jumps and some weird things happens!!!

Probably there's some index missing.
Can you please take a look? (I'm attaching a video)

[issue.mov.zip](https://github.com/ermalkaleci/CarbonKit/files/185992/issue.mov.zip)

Thank you in advance,

Best regards.

**Comment by ermalkaleci** [comment]
@egruttner 
Confirmed! you can call `setCurrentTabIndex:` on viewDidAppear: until I fix this issue

**Comment by egruttner** [comment]
Thanks for the quick reply.
Now it's working!
