### ISSUE TITLE
`self.toolbarHeight` is 40 as default, and it can not be prepared.

### ISSUE THREAD

**Issue by wanbok** [ermalkaleci/CarbonKit#85]
Hi,

I was trying to make toolbar's height to 48px. But CarbonTabSwipeNavigation still be only 44px, Even though I changed toolbar's height to 48px.
Also I found that `toolbarHeight` is only `40` constant.

If it is matter, I can PR about this issue.

**Comment by ermalkaleci** [comment]
Hey @wanbok  do you have any suggestion about feature or improvements?

**Comment by wanbok** [comment]
I'll check it on next Monday and I'll comment about it.
