### ISSUE TITLE
lost text when selected index tab

### ISSUE THREAD

**Issue by TrungVu37** [ermalkaleci/CarbonKit#89]
https://www.dropbox.com/s/5nltowh3a7vgnm6/Screen%20Shot%202016-04-05%20at%2014.23.27.png?dl=0

project sample
https://www.dropbox.com/s/pxyaii1qs4lzgzg/CarbonKit-master.zip?dl=0

**Comment by ermalkaleci** [comment]
@TrungVu37 please do not open an issue if you don't know what you're doing.
`[carbonTabSwipeNavigation setIndicatorHeight:40];`
