### ISSUE TITLE
DONE

### ISSUE THREAD

**Issue by TrungVu37** [ermalkaleci/CarbonKit#93]

**Comment by ermalkaleci** [comment]
@TrungVu37 what does "DONE" mean?

**Comment by TrungVu37** [comment]
i want hide navigation bar when scroll and i'm finish it, I used delegate, it's woking but not good :D, I think if you free, you can do more carbonkit have function "hide navigation bar when scroll". thanks

**Comment by ermalkaleci** [comment]
@TrungVu37  I want this feature too but unfortunately I have been really busy

**Comment by TrungVu37** [comment]
yes i know, if you have a free time because it's a product of you ^^ thanks

**Comment by ermalkaleci** [comment]
nope, It's an open source project

**Comment by TrungVu37** [comment]
oh, it's not of you. Realy

**Comment by ermalkaleci** [comment]
I mean it's an open source project, not a product

**Comment by TrungVu37** [comment]
can you support me this issue https://github.com/ermalkaleci/CarbonKit/issues/95
