### ISSUE TITLE
Combine CarbonTabSwipeNavigation with UITabbarViewController

### ISSUE THREAD

**Issue by TranChuong** [ermalkaleci/CarbonKit#94]
I have a issue when Combine CarbonTabSwipeNavigation with UITabbarViewController.
CarbonTabSwipeSegmentedControl is not correct position when I change tabviewcontroller.

Before
![simulator screen shot apr 15 2016 16 28 11](https://cloud.githubusercontent.com/assets/7924855/14557386/57be74ea-0327-11e6-8085-59acdab18144.png)

After
![simulator screen shot apr 15 2016 16 28 19](https://cloud.githubusercontent.com/assets/7924855/14557404/6208db70-0327-11e6-9509-bb9bb3b51675.png)

Can you help me in case?
Thanks

**Comment by ermalkaleci** [comment]
@TranChuong can you try adding another tap or increate tabWidth? I am afraid if this issue is cause due a small contentSize

**Comment by TranChuong** [comment]
Thanks @ermalkaleci 

It's fixed when I'm removed a line code in setup style for TabSwipeNavigation

[carbonTabSwipeNavigation setTabExtraWidth:self.view.width/4];
